### ISSUE TITLE
Add contact details to the Code of Conduct

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/taipei#2]
We've provided a draft Code of Conduct for you.  Currently this only has @smpebble's  email address listed for reporting purposes. It should either have @ccomeon's as well or use a shared email address that you both have access to. that needs an email address filled in for reporting purposes. (If using a personal email address rather than one for the group, please include your name as well.)

Please close this issue after **all** chapter organizers have reviewed the CoC thoroughly and confirmed they are comfortable enforcing it.

(This will need to be done before we can list your chapter on our website.)

**Optional:** Our tutorials are currently all in English, but If you decide that you'll be conducting your chapter events and repo discussions in a language other than English, you are welcome to update your Code of Conduct to the appropriate language. What's used right now is a custom Code of Conduct that mixes the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct) ([see available translations](https://www.contributor-covenant.org/translations)) with the [Conference Code of Conduct](http://confcodeofconduct.com/) ([see available translations](https://github.com/confcodeofconduct/confcodeofconduct.com)) to ensure it covers interactions both online and at events.

**Comment by ccomeon** [comment]
Simply added and updated my contact at #6 . @terichadbourne and @smpebble may review the changes. Will consider further changes and localization after getting in touch with the community.

**Comment by smpebble** [comment]
Thanks Kevin

> Simply added and updated my contact at #6 . @terichadbourne and @smpebble may review the changes. Will consider further changes and localization after getting in touch with the community.
